---
title: "Machine Learning - Classification of Exercises"
author: "cbcoursera1"
date: "Saturday, July 11, 2015"
output: html_document
---

```{r}

# Libraries

library(data.table)
library(caret)
library(doParallel)
registerDoParallel(cores=36) # EC2 c4.8xlarge

# Seed

set.seed(8675309)

# Scale of models

scale <- 0.01 # low for testing purposes

 
pml_write_files = function(x){
  n = length(x[, classe])
  print(class(x))
  for(i in 1:n){
    filename = paste0("problem_id_",x[i, problem_id], ".txt")
    print(paste0("problem_id_",x[i, problem_id], ".txt"))
    write.table(x[i, classe], file=filename, quote=FALSE, row.names=FALSE, col.names=FALSE)
  }
}

```

```{r}

# Get data

# download.file("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv", destfile = "pml-training.csv")
# download.file("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv", destfile = "pml-testing.csv")
# download.file("http://groupware.les.inf.puc-rio.br/public/papers/2013.Velloso.QAR-WLE.pdf", destfile = "databook.pdf", "wininet") # databook

# Read data into dat.table, drop row number

training <- fread("pml-training.csv", data.table = T)[, 1:160, with = F]
testing <- fread("pml-testing.csv", data.table = T)[, 1:160, with = F]
setkey(training, new_window)
setkey(testing, new_window)
training$classe <- as.factor(training$classe)

# Get rid of new window data in training

training <- training["no"]
setkey(training, V1)
setkey(testing, V1)

# Segment out applicable variables in training

training <- training[, c(3, 8:11, 37:49, 60:68, 84:86, 102, 113:124, 140, 151:160), with = F]

# Split training into train and test

inTrain <- createDataPartition(y = training$classe, p = 0.6, list = F)
train.train <- training[as.vector(inTrain)]
train.test <- training[as.vector(-inTrain)]

```

```{r}

models <- list("rf" = list(model = c()))

# Try training for fun

models$rf$model <- train(classe ~ ., method = "rf", trControl = trainControl(method = "cv"), data = as.data.frame(train.train[as.vector(createDataPartition(y = train.train$classe, p = scale, list = F))]))

models$rf$conf <- confusionMatrix(train.test$classe, predict(object = models$rf$model, newdata = train.test[, c(1:53), with = F])) 

models$gbm$model <- train(classe ~ ., method = "gbm", data = as.data.frame(train.train[as.vector(createDataPartition(y = train.train$classe, p = scale, list = F))]))

models$gbm$conf <- confusionMatrix(train.test$classe, predict(object = models$gbm$model, newdata = train.test[, c(1:53), with = F]))

```

```{r}

# Save and load training models

saveRDS(models, file="models.rds")
models <- readRDS("models.rds")

```

```{r}

# Solutions

# testing$classe <- predict(object = models$rf$model, newdata = testing)

testing$classe <- predict(object = models$gbm$model, newdata = testing)

pml_write_files(testing[, classe])

```

# APPENDIX

Citation:

Velloso, E.; Bulling, A.; Gellersen, H.; Ugulino, W.; Fuks, H. Qualitative Activity Recognition of Weight Lifting Exercises. Proceedings of 4th International Conference in Cooperation with SIGCHI (Augmented Human '13) . Stuttgart, Germany: ACM SIGCHI, 2013.

Read more: http://groupware.les.inf.puc-rio.br/har#dataset#ixzz3fcXZS8WB
